version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # Management Plugin

  inventory-service:
    build:
      context: ./inventory-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/inventory_db
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3001:3001"

  bidding-service:
    build:
      context: ./bidding-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bidding_db
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3002:3002"

  recommendation-service:
    build:
      context: ./recommendation-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/recommendation_db
      - RABBITMQ_URI=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3003:3003"